kind = "mobile"
previewPath = "/"
title = "CookWise"
version = "1.0.0"
id = "artifacts/cookwise"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19983

[services.development]
run = "pnpm --filter @workspace/cookwise run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cookwise", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/cookwise", "run", "serve" ]

[services.env]
PORT = "19983"
BASE_PATH = "/"
